import pytest

from avatar_pipeline.media import validate_media_plan
from avatar_pipeline.models import MediaKind, MediaPlan, MediaSegment, NewsScript, ScriptSegment

HOST_ID = "host-main"


def script():
    return NewsScript(
        title="标题",
        spoken_segments=[ScriptSegment(id="s1", kind="fact", text="事实", source_ids=["src"])],
        source_ids=["src"],
    )


def anchor(segment_id: str, start: float, end: float) -> MediaSegment:
    return MediaSegment(
        id=segment_id,
        kind=MediaKind.ANCHOR,
        start_seconds=start,
        end_seconds=end,
        script_segment_id="s1",
        host_id=HOST_ID,
    )


def plan(*segments: MediaSegment, duration_seconds: float) -> MediaPlan:
    return MediaPlan(
        duration_seconds=duration_seconds,
        host_id=HOST_ID,
        segments=list(segments),
    )


def test_original_media_requires_provenance():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="o",
            kind=MediaKind.ORIGINAL_NEWS,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            source_id="src",
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="provenance"):
        validate_media_plan(media_plan, script())


def test_original_media_source_must_be_declared_by_script():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="o",
            kind=MediaKind.ORIGINAL_NEWS,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            source_id="undeclared",
            provenance="source clip 00:01-00:06",
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="declared by script"):
        validate_media_plan(media_plan, script())


def test_ai_demo_requires_disclosure():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="disclosure"):
        validate_media_plan(media_plan, script())


def test_media_plan_accepts_anchor_original_news_anchor():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="o",
            kind=MediaKind.ORIGINAL_NEWS,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            source_id="src",
            provenance="src 00:01-00:06",
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    validate_media_plan(media_plan, script())


def test_media_plan_accepts_ai_fallback_with_explicit_disclosure():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            disclosure="AI生成示意画面",
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    validate_media_plan(media_plan, script())


def test_media_plan_rejects_non_alternating_timeline():
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="o",
            kind=MediaKind.ORIGINAL_NEWS,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            source_id="src",
            provenance="src 00:01-00:06",
        ),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=10,
            end_seconds=15,
            script_segment_id="s1",
            disclosure="AI生成示意画面",
        ),
        anchor("a2", 15, 20),
        duration_seconds=20,
    )

    with pytest.raises(ValueError, match="alternate"):
        validate_media_plan(media_plan, script())


@pytest.mark.parametrize(
    "disclosure",
    [
        "AI生成示意画面",
        "AI 生成示意画面",
        "人工智能生成示意画面",
        "AI-generated illustrative footage",
        "AI generated illustrative footage",
        "illustrative footage generated by AI",
    ],
)
def test_ai_demo_accepts_explicit_generation_disclosures(disclosure):
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            disclosure=disclosure,
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    validate_media_plan(media_plan, script())


@pytest.mark.parametrize(
    "disclosure",
    [
        "paid archival footage",
        "available footage",
        "news illustration",
        "示意画面",
    ],
)
def test_ai_demo_rejects_disclosure_without_explicit_ai_generation(disclosure):
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            disclosure=disclosure,
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="AI generation disclosure"):
        validate_media_plan(media_plan, script())


@pytest.mark.parametrize(
    ("source_id", "provenance"),
    [
        ("   ", "source clip 00:01-00:06"),
        ("src", "   "),
        ("   ", "   "),
    ],
)
def test_original_media_rejects_blank_source_or_provenance(source_id, provenance):
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="o",
            kind=MediaKind.ORIGINAL_NEWS,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            source_id=source_id,
            provenance=provenance,
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="source_id and provenance"):
        validate_media_plan(media_plan, script())


@pytest.mark.parametrize(
    "disclosure",
    [
        "not AI-generated footage",
        "non-AI-generated archival footage",
        "不是AI生成画面",
        "非人工智能生成画面",
    ],
)
def test_ai_demo_rejects_negated_generation_disclosure(disclosure):
    media_plan = plan(
        anchor("a1", 0, 5),
        MediaSegment(
            id="d",
            kind=MediaKind.AI_DEMO,
            start_seconds=5,
            end_seconds=10,
            script_segment_id="s1",
            disclosure=disclosure,
        ),
        anchor("a2", 10, 15),
        duration_seconds=15,
    )

    with pytest.raises(ValueError, match="AI generation disclosure"):
        validate_media_plan(media_plan, script())
